apiVersion: v1
kind: Service
metadata:
  name: cloudscale-web
  labels:
    app: cloudscale-web

spec:
  type: LoadBalancer

  selector:
    app: cloudscale-web

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000